version: "1"
services:
  frontend:
    build: ./docker/
    ports:
      - "0.0.0.0:${VITE_APP_PORT}:80"
      - "0.0.0.0:${VITE_APP_PORT_SSL}:443"
    volumes:
      - ./dist:/var/www/html/public
    restart: always
