version: "1"
services:
  frontend:
    build: .
    ports:
      - "0.0.0.0:${VITE_APP_PORT}:80"
      - "0.0.0.0:${VITE_APP_PORT_SSL}:443"
    command: sh -c "apachectl -D FOREGROUND"
    restart: always